apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "omnifyproduct.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.api }}
        - {{ .Values.ingress.hosts.app }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.hosts.api }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "omnifyproduct.fullname" . }}-api
                port:
                  number: 8000
    - host: {{ .Values.ingress.hosts.app }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "omnifyproduct.fullname" . }}-frontend
                port:
                  number: 80

