apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnifyproduct.fullname" . }}-api
spec:
  selector:
    app: {{ include "omnifyproduct.fullname" . }}-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnifyproduct.fullname" . }}-frontend
spec:
  selector:
    app: {{ include "omnifyproduct.fullname" . }}-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP

