apiVersion: v1
kind: Service
metadata:
  name: omnify-api
spec:
  selector:
    app: omnify-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: omnify-frontend
spec:
  selector:
    app: omnify-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP

